# Properties of the language to be used
Language:
  operators: [['+', 10], ['-', 6], ['*', 6], ['/', 3], ['^2', 3], ['^3', 1], ['inv', 3],
              ['^4', 1], ['log', 2], ['exp', 1], ['sqrt', 1], ['sin', 2], ['cos', 2]]
  prob_terminal: 0.5
  restrictions: ['no_inverse_parent', 'no_sqrt_in_log', 'no_double_division', 'no_sqrt_in_sqrt', 
                 'no_trigo_in_log', 'no_trigo_offspring', 'no_log_in_trigo']
  max_variables: 3
  max_len: 15
  use_constants: True
  prob_add_const: 0.05
  prob_mult_const: 0.3


# Properties of the model
Model:
  from_path: '/Users/UX331U/Desktop/2022-08-22/14-42-22/Weights/log_epoch=20_val_loss=1.08.ckpt'
  dim_hidden: 512
  dropout: 0.0
  dim_feedforward: 512
  sinusoidal_embeddings: False
  bit16: True
  num_heads: 8
  inducing_points: 50
  norm_encoder: True
  layers_encoder: 5
  layers_decoder: 5
  num_features: 10

# Train configuration
Train:
  Supervised_Training:
    n_functions_train: 10000
    n_functions_test: 1000
    batch_size: 8
    lr: 0.00003
    gpus: [0]
    epochs: 32
    precision: 16
    log_frequency: 16

  RL_Training:
    episodes: 1024
    complexity_penalty: 0.05
    squishing_scale: 5
    lr: 0
    control_each: 128
    save_each: 512
    model_path: ''