# Properties of the language to be used
Language:
  operators: [['+', 10], ['-', 6], ['*', 6], ['/', 3], ['^2', 3], ['^3', 1], ['inv', 3],
              ['^4', 1], ['log', 2], ['exp', 1], ['sqrt', 1], ['sin', 2], ['cos', 2]]
  prob_terminal: 0.5
  restrictions: ['no_inverse_parent', 'no_sqrt_in_log', 'no_double_division', 'no_sqrt_in_sqrt', 
                 'no_trigo_in_log', 'no_trigo_offspring', 'no_log_in_trigo']
  max_variables: 3
  max_len: 15
  use_constants: True
  prob_add_const: 0.08
  prob_mult_const: 0.3
  p_degenerated_program: 0.08

# Properties of the model
Model:
  from_path: '/home/gridsan/amorenas/ETIN/outputs/2022-09-23/20-26-50/Weights/log_epoch=18_val_loss=0.85.ckpt'
  dim_hidden: 512
  dropout: 0.0
  dim_feedforward: 512
  sinusoidal_embeddings: False
  bit16: True
  num_heads: 8
  inducing_points: 50
  norm_encoder: True
  layers_encoder: 5
  layers_decoder: 5
  num_features: 10

# Train configuration
Train:
  Supervised_Training:
    n_functions_train: 10000
    n_functions_test: 10000
    batch_size: 64
    lr: 0.000003
    gpus: 1
    epochs: 32
    precision: 16
    log_frequency: 16
    seed: null

  RL_Training:
    episodes: 50000
    num_expressions: 2
    complexity_penalty: 0.00
    squishing_scale: 1
    lr: 0.0000001
    discover_probability: 1.
    decay: 1.
    control_each: 100
    save_each: 10000
    model_path: '/home/gridsan/amorenas/ETIN3/outputs/prueba_con_baseline1'
    seed: 69
    entropy_weight: 0.05
    with_baseline: True